# Generated by Django 3.0.3 on 2020-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
